[package]
name = "footile"
version = "0.3.0"
authors = ["Douglas Lau <doug.p.lau@gmail.com>"]
description = "A 2D vector graphics library"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/footile"
homepage = "https://github.com/DougLau/footile"
repository = "https://github.com/DougLau/footile"
readme = "README.md"

[dependencies]
png = "0.10"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "fishyb"
harness = false

[features]
default = ["use-simd"]
use-simd = []
