[package]
name = "footile"
version = "0.3.1"
authors = ["Douglas Lau <doug.p.lau@gmail.com>"]
description = "A 2D vector graphics library"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/footile"
homepage = "https://github.com/DougLau/footile"
repository = "https://github.com/DougLau/footile"
readme = "README.md"
edition = "2018"

[dependencies]
pix = "0.6.1"

[dev-dependencies]
criterion = "0.2"
png_pong = "0.0"
pixops = "0.0"

[[bench]]
name = "fishyb"
harness = false

[features]
default = ["use-simd"]
use-simd = []

[replace]
"pix:0.6.1" = { path = "../pix" } # "../../pix"
"pixops:0.0.1" = { path = "../pixops" } # "../../pixops"
"png_pong:0.0.2" = { path = "../png_pong" }
